name: C++ tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install build environment
        run: sudo apt-get install -y build-essential libgtest-dev
      - name: Run tests
        run: |
          cd tests
          g++ main.cpp -std=c++17 -I../ -lgtest -lgtest_main -pthread
          ./a.out

