name: Python tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install build environment
        run: sudo apt-get install -y build-essential libpython3-dev python3-venv
      - name: Run tests
        run: |
          cd python
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements-dev.txt
          python setup.py install
          pytest

